var searchData=
[
  ['element_20asymmetric_20cryptography_0',['Secure Element Asymmetric Cryptography',['../group__se__asymmetric.html',1,'']]],
  ['element_20authenticated_20encryption_20with_20additional_20data_1',['Secure Element Authenticated Encryption with Additional Data',['../group__se__aead.html',1,'']]],
  ['element_20driver_20initialization_2',['Secure element driver initialization',['../group__se__init.html',1,'']]],
  ['element_20driver_20registration_3',['Secure element driver registration',['../group__se__registration.html',1,'']]],
  ['element_20key_20derivation_20and_20agreement_4',['Secure Element Key Derivation and Agreement',['../group__driver__derivation.html',1,'']]],
  ['element_20key_20management_5',['Secure Element Key Management',['../group__se__key__management.html',1,'']]],
  ['element_20message_20authentication_20codes_6',['Secure Element Message Authentication Codes',['../group__se__mac.html',1,'']]],
  ['element_20symmetric_20ciphers_7',['Secure Element Symmetric Ciphers',['../group__se__cipher.html',1,'']]],
  ['encryption_20with_20additional_20data_8',['Encryption with Additional Data',['../group__accel__aead.html',1,'Hardware-Accelerated Authenticated Encryption with Additional Data'],['../group__se__aead.html',1,'Secure Element Authenticated Encryption with Additional Data']]],
  ['encryption_20with_20associated_20data_20aead_9',['Authenticated encryption with associated data (AEAD)',['../group__aead.html',1,'']]],
  ['endpointresolver_20class_10',['EndpointResolver class',['../group__drivers___endpoint_resolver.html',1,'']]],
  ['entropy_20generation_11',['Entropy Generation',['../group__driver__rng.html',1,'']]],
  ['error_20codes_12',['Error Codes',['../group__nfc-errors.html',1,'']]],
  ['error_20codes_13',['Error codes',['../group__error.html',1,'']]],
  ['error_20functions_14',['Error functions',['../group__platform__error.html',1,'']]],
  ['event_20classes_15',['Event classes',['../group__events___event.html',1,'']]],
  ['eventflags_20class_16',['EventFlags class',['../group__rtos___event_flags.html',1,'']]],
  ['eventqueue_20class_17',['EventQueue class',['../group__events___event_queue.html',1,'']]],
  ['events_18',['Events',['../group__events-public-api.html',1,'']]],
  ['events_20macros_19',['Events Macros',['../group__hal___i2_c_events.html',1,'I2C Events Macros'],['../group___serial_r_x_events.html',1,'Serial RX Events Macros'],['../group___serial_t_x_events.html',1,'Serial TX Events Macros'],['../group__hal___s_p_i_events.html',1,'SPI Events Macros']]],
  ['experimental_20apis_20',['Experimental APIs',['../group__mbed-os-experimental.html',1,'']]],
  ['export_21',['Key import and export',['../group__import__export.html',1,'']]]
];
