var searchData=
[
  ['macrocell_20hal_20api_0',['Instrumented Trace Macrocell HAL API',['../group__itm__hal.html',1,'']]],
  ['macros_1',['Macros',['../group__hal___i2_c_events.html',1,'I2C Events Macros'],['../group___serial_r_x_events.html',1,'Serial RX Events Macros'],['../group___serial_t_x_events.html',1,'Serial TX Events Macros'],['../group__hal___s_p_i_events.html',1,'SPI Events Macros']]],
  ['macros_2',['macros',['../group__platform___assert.html',1,'Assert macros'],['../group__platform__preprocessor.html',1,'preprocessor macros']]],
  ['mail_20class_3',['Mail class',['../group__rtos___mail.html',1,'']]],
  ['management_4',['Secure Element Key Management',['../group__se__key__management.html',1,'']]],
  ['management_5',['Key management',['../group__key__management.html',1,'']]],
  ['management_20functions_6',['management functions',['../group__platform__mpu__mgmt.html',1,'MPU management functions'],['../group__platform__power__mgmt.html',1,'Power management functions']]],
  ['manager_20api_7',['Sleep manager API',['../group__hal__sleep__manager.html',1,'']]],
  ['manager_20api_20tests_8',['Sleep manager API tests',['../group__hal__sleep__manager__tests.html',1,'']]],
  ['mbed_20thread_9',['Mbed Thread',['../group__mbed__thread.html',1,'']]],
  ['mbedcrc_20class_10',['MbedCRC class',['../group__drivers___mbed_c_r_c.html',1,'']]],
  ['mem_5ftrace_20functions_11',['mem_trace functions',['../group__platform__mem__trace.html',1,'']]],
  ['memorypool_20class_12',['MemoryPool class',['../group__rtos___memory_pool.html',1,'']]],
  ['message_20authentication_20code_13',['Hardware-Accelerated Message Authentication Code',['../group__accel__mac.html',1,'']]],
  ['message_20authentication_20codes_14',['Secure Element Message Authentication Codes',['../group__se__mac.html',1,'']]],
  ['message_20authentication_20codes_15',['Message authentication codes',['../group___m_a_c.html',1,'']]],
  ['message_20digests_16',['Hardware-Accelerated Message Digests',['../group__driver__digest.html',1,'']]],
  ['message_20digests_17',['Message digests',['../group__hash.html',1,'']]],
  ['microsecond_20ticker_18',['Microsecond Ticker',['../group__hal__us__ticker.html',1,'']]],
  ['microsecond_20ticker_20tests_19',['Microsecond Ticker tests',['../group__hal__us__ticker__tests.html',1,'']]],
  ['midimessage_20class_20',['MIDIMessage class',['../group__drivers___m_i_d_i_message.html',1,'']]],
  ['mktime_20functions_21',['mktime functions',['../group__platform__mktime.html',1,'']]],
  ['mpu_20hal_22',['MPU hal',['../group__hal__mpu.html',1,'']]],
  ['mpu_20hal_20tests_23',['MPU hal tests',['../group__hal__mpu__tests.html',1,'']]],
  ['mpu_20management_20functions_24',['MPU management functions',['../group__platform__mpu__mgmt.html',1,'']]],
  ['mutex_20class_25',['Mutex class',['../group__rtos___mutex.html',1,'']]]
];
