# MbedCE upload configuration for the NUCLEO_WB09KE ST-LINK interface.
set(UPLOAD_METHOD_DEFAULT MBED)

set(MBED_UPLOAD_ENABLED TRUE)
set(MBED_RESET_BAUDRATE 115200)

set(STM32CUBE_UPLOAD_ENABLED TRUE)
set(STM32CUBE_CONNECT_COMMAND -c port=SWD reset=HWrst)
set(STM32CUBE_GDBSERVER_ARGS --swd)
