/* Copyright (c) 2026 MbedCE Community Contributors (Jan Kamidra)
 * SPDX-License-Identifier: Apache-2.0
 */
#include "PeripheralPins.h"
#include "mbed_toolchain.h"

MBED_WEAK const PinMap PinMap_GPIO[] = {
    {PA_0, 0, GPIO_NOPULL}, {PA_1, 0, GPIO_NOPULL},
    {PA_2, 0, GPIO_NOPULL}, {PA_3, 0, GPIO_NOPULL},
    {PA_8, 0, GPIO_NOPULL}, {PA_9, 0, GPIO_NOPULL},
    {PA_10, 0, GPIO_NOPULL}, {PA_11, 0, GPIO_NOPULL},
    {PB_0, 0, GPIO_NOPULL}, {PB_1, 0, GPIO_NOPULL},
    {PB_2, 0, GPIO_NOPULL}, {PB_3, 0, GPIO_NOPULL},
    {PB_4, 0, GPIO_NOPULL}, {PB_5, 0, GPIO_NOPULL},
    {PB_6, 0, GPIO_NOPULL}, {PB_7, 0, GPIO_NOPULL},
    {PB_12, 0, GPIO_NOPULL}, {PB_13, 0, GPIO_NOPULL},
    {PB_14, 0, GPIO_NOPULL}, {PB_15, 0, GPIO_NOPULL},
    {NC, NC, 0}
};

MBED_WEAK const PinMap PinMap_UART_TX[] = {
    {PA_1,  UART_1,   STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF2_USART1)},
    {PA_9,  UART_1,   STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF0_USART1)},
    {PB_15, UART_1,   STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF6_USART1)},
    {PB_3,  LPUART_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF1_LPUART1)},
    {PB_4,  LPUART_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF0_LPUART1)},
    {PB_6,  LPUART_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF3_LPUART1)},
    {NC, NC, 0}
};

MBED_WEAK const PinMap PinMap_UART_RX[] = {
    {PA_8,  UART_1,   STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF0_USART1)},
    {PB_0,  UART_1,   STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF0_USART1)},
    {PB_14, UART_1,   STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF6_USART1)},
    {PB_5,  LPUART_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF0_LPUART1)},
    {PB_7,  LPUART_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF3_LPUART1)},
    {NC, NC, 0}
};
