# This workflow detects if any Docker-related files have changed. New Mbed CE Docker containers will only be pushed to
# the GitHub Container Registry from PRs only in the event of changes to the Docker environment.
name: Detect Docker Changes

on:
  pull_request:
  push:

jobs:
  detect-docker-changes:
    runs-on: ubuntu-latest

    outputs:
      docker_changed: ${{ steps.changes.outputs.docker }}

    steps:
      - uses: actions/checkout@v6

      - name: Detect Docker changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            docker:
              - 'docker_images/**'
              - '.github/workflows/docker_management.*'
              - '.github/workflows/ci_scripts/**'
              - '**/Dockerfile'
