name: test building multiple executables with CMake

on: [pull_request]

jobs:
  multiple-executables-example:
    uses: ./.github/workflows/ci-multiple-executables.yml
    with:
      image: ghcr.io/mbed-ce/mbed-ce-env:main
